export const PERMISSION_CATALOG = {
  PLATFORM: {
    'platform.orgs.read': { description: 'View organizations', riskLevel: 'LOW' },
    'platform.orgs.manage': { description: 'Manage organizations', riskLevel: 'HIGH' },
    'platform.users.read': { description: 'View all users', riskLevel: 'LOW' },
    'platform.users.manage': { description: 'Manage all users', riskLevel: 'HIGH' },
    'platform.billing.read': { description: 'View platform billing', riskLevel: 'MED' },
    'platform.billing.manage': { description: 'Manage platform billing', riskLevel: 'HIGH' },
    'platform.audit.read': { description: 'View platform audit logs', riskLevel: 'MED' },
    'platform.security.read': { description: 'View security events', riskLevel: 'MED' },
    'platform.security.manage': { description: 'Manage security settings', riskLevel: 'HIGH' },
    'platform.support.impersonate': { description: 'Impersonate users for support', riskLevel: 'HIGH' },
    'platform.iam.catalog.read': { description: 'View IAM catalog', riskLevel: 'LOW' },
    'platform.iam.catalog.manage': { description: 'Manage IAM catalog', riskLevel: 'HIGH' },
  },
  ORG: {
    'org.users.read': { description: 'View organization users', riskLevel: 'LOW' },
    'org.users.invite': { description: 'Invite users to organization', riskLevel: 'MED' },
    'org.users.update': { description: 'Update user details', riskLevel: 'MED' },
    'org.users.suspend': { description: 'Suspend/reactivate users', riskLevel: 'HIGH' },
    'org.users.remove': { description: 'Remove users from organization', riskLevel: 'HIGH' },
    'org.roles.read': { description: 'View roles', riskLevel: 'LOW' },
    'org.roles.manage': { description: 'Manage roles and permissions', riskLevel: 'HIGH' },
    'org.teams.read': { description: 'View teams', riskLevel: 'LOW' },
    'org.teams.manage': { description: 'Manage teams', riskLevel: 'HIGH' },
    'org.api_keys.read': { description: 'View API keys', riskLevel: 'LOW' },
    'org.api_keys.manage': { description: 'Manage API keys', riskLevel: 'HIGH' },
    'org.threats.read': { description: 'View threats', riskLevel: 'LOW' },
    'org.threats.investigate': { description: 'Investigate threats', riskLevel: 'MED' },
    'org.threats.dismiss': { description: 'Dismiss threats', riskLevel: 'MED' },
    'org.threats.remediate': { description: 'Remediate threats', riskLevel: 'HIGH' },
    'org.threats.export': { description: 'Export threat data', riskLevel: 'MED' },
    'org.identities.read': { description: 'View identities', riskLevel: 'LOW' },
    'org.identities.manage': { description: 'Manage identities', riskLevel: 'HIGH' },
    'org.identities.rotate_credentials': { description: 'Rotate credentials', riskLevel: 'HIGH' },
    'org.identities.quarantine': { description: 'Quarantine identities', riskLevel: 'HIGH' },
    'org.nhiti.read': { description: 'View NHITI data', riskLevel: 'LOW' },
    'org.nhiti.share': { description: 'Share NHITI data', riskLevel: 'HIGH' },
    'org.integrations.read': { description: 'View integrations', riskLevel: 'LOW' },
    'org.integrations.manage': { description: 'Manage integrations', riskLevel: 'HIGH' },
    'org.audit.read': { description: 'View audit logs', riskLevel: 'MED' },
    'org.audit.export': { description: 'Export audit logs', riskLevel: 'MED' },
    'org.compliance.read': { description: 'View compliance reports', riskLevel: 'LOW' },
    'org.compliance.manage': { description: 'Manage compliance settings', riskLevel: 'HIGH' },
    'org.billing.read': { description: 'View billing information', riskLevel: 'LOW' },
    'org.billing.manage': { description: 'Manage billing and subscriptions', riskLevel: 'HIGH' },
    'org.invoices.read': { description: 'View invoices', riskLevel: 'LOW' },
    'org.settings.read': { description: 'View organization settings', riskLevel: 'LOW' },
    'org.settings.manage': { description: 'Manage organization settings', riskLevel: 'HIGH' },
  },
} as const;

export const ABAC_RULES = {
  AUDITOR_DENIALS: [
    'org.threats.remediate',
    'org.identities.rotate_credentials',
    'org.identities.quarantine',
    'org.roles.manage',
    'org.teams.manage',
    'org.api_keys.manage',
  ],
} as const;

export const LEGACY_ROLE_MAPPING = {
  super_admin: {
    scope: 'PLATFORM' as const,
    permissions: [
      'platform.orgs.read',
      'platform.orgs.manage',
      'platform.users.read',
      'platform.users.manage',
      'platform.billing.read',
      'platform.billing.manage',
      'platform.audit.read',
      'platform.security.read',
      'platform.security.manage',
      'platform.support.impersonate',
      'platform.iam.catalog.read',
      'platform.iam.catalog.manage',
    ],
  },
  admin: {
    scope: 'ORG' as const,
    permissions: [
      'org.users.read',
      'org.users.invite',
      'org.users.update',
      'org.users.suspend',
      'org.users.remove',
      'org.roles.read',
      'org.roles.manage',
      'org.teams.read',
      'org.teams.manage',
      'org.api_keys.read',
      'org.api_keys.manage',
      'org.threats.read',
      'org.threats.investigate',
      'org.threats.dismiss',
      'org.threats.remediate',
      'org.threats.export',
      'org.identities.read',
      'org.identities.manage',
      'org.identities.rotate_credentials',
      'org.identities.quarantine',
      'org.nhiti.read',
      'org.nhiti.share',
      'org.integrations.read',
      'org.integrations.manage',
      'org.audit.read',
      'org.audit.export',
      'org.compliance.read',
      'org.compliance.manage',
      'org.billing.read',
      'org.billing.manage',
      'org.invoices.read',
      'org.settings.read',
      'org.settings.manage',
    ],
  },
  analyst: {
    scope: 'ORG' as const,
    permissions: [
      'org.users.read',
      'org.threats.read',
      'org.threats.investigate',
      'org.threats.dismiss',
      'org.threats.remediate',
      'org.threats.export',
      'org.identities.read',
      'org.identities.manage',
      'org.identities.rotate_credentials',
      'org.identities.quarantine',
      'org.nhiti.read',
      'org.integrations.read',
      'org.audit.read',
      'org.compliance.read',
    ],
  },
  auditor: {
    scope: 'ORG' as const,
    permissions: [
      'org.users.read',
      'org.threats.read',
      'org.identities.read',
      'org.audit.read',
      'org.audit.export',
      'org.compliance.read',
      'org.billing.read',
      'org.invoices.read',
    ],
  },
  viewer: {
    scope: 'ORG' as const,
    permissions: [
      'org.threats.read',
      'org.identities.read',
      'org.compliance.read',
    ],
  },
};
